### ISSUE TITLE
Visualizzazioni Force-Directed Graph

### ISSUE THREAD

**Issue by LorenzoOnelia** [merlunipd/login-warrior#191]

**Comment by MattiaZanellato** [comment]
# Idee visualizzazione
1. Ogni nodo è un’azione (login, logout, errore) → risulterebbero troppi punti
2. Ogni nodo è un utente
    - nodo colorato in base al rapporto successi/insuccessi durante il login?
    - link tra utenti che hanno il rapporto successi/insuccessi simile? In modo da raggruppare tra di loro le persone sospette e quelle non sospette (magari con colori diversi)
    - link in base a orari simili per vedere quali utenti hanno orari simili? Abbastanza inutile mi viene da dire

## Idea 1
Come detto sopra risulterebbero troppi punti

## Idea 2
Nodo → utente
Link → rapporto simile tra utenti
Utilizzo:
- per ogni utente viene disegnato un nodo
- utenti con rapporti simili hanno un link tra di loro, come? Entro un determinato range? Più il rapporto è vicino e più è forte il collegamento?

# Utilizzo
Per crea il grafico serve:
- lista di nodi
- lista di connessioni
