### ISSUE TITLE
Aggiornare NdP e PdQ

### ISSUE THREAD

**Issue by marco-mazzucato** [merlunipd/login-warrior#206]
controllare NdP e vedere se ci sono dei processi abbandonati da togliere (es. diagrammi di Gantt) + aggiungere in miglioramento in PdQ.

**Comment by marco-mazzucato** [comment]
Nelle NdP nella parte dove vengono descritti i documenti bisogna aggiungere _Specifica Architetturale_ anche chiamata _SA_. Poi bisogna aggiungerla anche al glossario (per la definizione basta guardare la mail di Tullio)

**Comment by LorenzoOnelia** [comment]
Ok capo
