### ISSUE TITLE
Aggiornamento NdP metriche

### ISSUE THREAD

**Issue by Emanuele999-it** [merlunipd/login-warrior#224]
Aggiornare le NdP con le nuove metriche preseni nel PdQ, il significato e la formule per calcolarle sono presenti nel file docs nella cartella "Sprint" di Drive

**Comment by Emanuele999-it** [comment]
Anche questa issue è da chiudere. Il documento da aggiornare non era l'AdR, bensì le NdP (#240)

**Comment by MattiaZanellato** [comment]
> Anche questa issue è da chiudere. Il documento da aggiornare non era l'AdR, bensì le NdP (#240)

Quindi le AdR sono già apposto giusto?

**Comment by Emanuele999-it** [comment]
> > Anche questa issue è da chiudere. Il documento da aggiornare non era l'AdR, bensì le NdP (#240)
> 
> Quindi le AdR sono già apposto giusto?

Sì perché l'aggiornamento le metriche coinvolge solo le NdP e il PdQ
