### ISSUE TITLE
Inserire il filtro “logout” sullo scatter plot 2

### ISSUE THREAD

**Issue by LorenzoOnelia** [merlunipd/login-warrior#273]

**Comment by riccardo-contin** [comment]
Ma questo è necessario? Quando era stato fatto il grafico era stato fatto direttamente senza i logout. Nel caso bisognerebbe mettere i logout nel grafico e poi inserire il filtro

**Comment by LorenzoOnelia** [comment]
Ok allora pacco. Avevo chiesto quando non c'eri e nessuno aveva detto nulla. Se è stato fatto apposta lasciamolo così!

**Comment by mamprinmarco** [comment]
E io che stavo per farlo

**Comment by LorenzoOnelia** [comment]
rip
