### ISSUE TITLE
Fix Norme di Progetto

### ISSUE THREAD

**Issue by morokuz** [merlunipd/login-warrior#28]
Durante la riunione del *22/12/2021* sono emerse alcune correzioni da fare al documento Norme di Progetto.

**Correzioni generali**:
- Rendere coerente il documento con le convenzioni di stile stabilite dal gruppo e riportate nel documento stesso (stile di testo, norme tipografiche, etc...) (**da rivedere alla fine poiché alcuni cambiamenti saranno oggetto della sezione seguente "Correzioni specifiche"**);
- Parole inglesi: non utilizzare la "s" per i plurali quando si scrivono parole inglesi in un testo in italiano (e.g. "file" no "files");
- TODO: rivedere e implementare dove possibile le parti etichettate come TODO (in rosso nel PDF, comando `\todo{...}` in latex);

**Correzioni specifiche**:
- *[2 Processi Primari]* "Fornitura" va prima di "Sviluppo";
- *[2.1.3 Analisi dei Requisiti]* Casi d'uso: aggiungere punto tra caso d'uso e sottocaso (`UC[Numero caso d’uso].[Sottocaso]`);
- *[2.1.3 Analisi dei Requisiti]* Struttura dei requisiti: capire come usare "Tipologia" (argomentare se utile, rimuovere altrimenti);
- *[3.1.4 Ciclo di vita di un documento]* Non utilizziamo più Trello per processi primari o di supporto ma utilizziamo GitHub (Issues, Milestone, Projects, etc...) (Trello rimane per gestire i processi organizzativi);
- *[3.1.6 Documenti prodotti]* Documenti informali: solo quelli utilizzati su Google Drive condiviso, gli altri sono tutti formali (inclusi i *Verbali*). Rimuovere la distinzione tra "Interni" / "Esterni";
- *[3.1.6 Documenti prodotti]* Documenti formali: aggiungere "manuale utente", "specifica architetturale"?;
- *[3.1.12 Verbali]* Maiuscola nell'elenco;
- *[3.1.14 Stile di testo]* Grassetto solo per le parole ritenute particolarmente importanti, no obbligo per elenchi puntati;
- *[3.1.15 Norme tipografiche]* Lettera minuscola dopo i due punti (aggiungere e correggere in tutto il documento);
- *[3.1.15 Norme tipografiche]* Ruoli: con la maiuscola (e.g. "Responsabile di Progetto") (aggiungere e correggere in tutto il documento);
- *[3.1.15 Norme tipografiche]* Documenti: scritti per esteso a meno di ripetizioni fastidiose, con la maiuscola come i ruoli (e.g. "Norme di Progetto");
- *[3.1.17 Sigle]* Nomi e sigle in corsivo;
- *[3.2.2 Aspettative]* Mancano i punti e virgola e il punto finale;
- *[3.2.4 Versionamento]* Rivedere questa sotto-sezione;
- *[3.2.6 Struttura repository]* In "Organizzazione del repository - Rami secondari...": "unititi";
- *[3.2.6 Struttura repository]* Citare "GitHub Flow" come best practice adottata;
- *[3.4.2 Descrizione]* Tipografia: punti e virgola elenchi;
- *[3.4.3 Indicazioni]* Tipografia: punti e virgola elenchi;
- *[3.4.4 Verifica della documentazione]* Tipografia: punti e virgola elenchi;
- *[3.4.4 Verifica della documentazione]* "Controllo della stesura del documento" -> " Controllo dell'aderenza alle convenzioni tipografiche e di stile adottate" (il documento è chiaramente già stato scritto);
- *[4.1.1 Coordinamento]* "Riunioni... Scaletta: ...": "segue usa" invece di "segue una";
- *[4.2.1 Strumenti]* Sezione GitHub: inserire link correttamente;
- *[4.2 Infrastruttura]* Generalmente non segue le convenzioni tipografiche e di stile adottate, rivedere con attenzione (poiché scritta prima della formalizzazione delle regole di stile);
- *[4.3 Miglioramento]* Segnare come TODO;
- *[4.4 Formazione]* 
  - Documentazione generica di overleaf invece che il "30 minutes";
  - Spostare il link al "generatore tabelle latex" su Drive ed eliminare da qui;
  - Aggiungere come sottopunti a GitHub:
    - Git: https://docs.github.com/en/get-started/using-git/about-git;
    - GitHub Flow: https://docs.github.com/en/get-started/quickstart/github-flow.

**Comment by LorenzoOnelia** [comment]
Resta da fare:

Correzioni generali:

- Rendere coerente il documento con le convenzioni di stile stabilite dal gruppo e riportate nel documento stesso (stile di testo, norme tipografiche, etc...) (da rivedere alla fine poiché alcuni cambiamenti saranno oggetto della sezione seguente "Correzioni specifiche");
- Parole inglesi: non utilizzare la "s" per i plurali quando si scrivono parole inglesi in un testo in italiano (e.g. "file" no "files");
- TODO: rivedere e implementare dove possibile le parti etichettate come TODO (in rosso nel PDF, comando \todo{...} in latex);

**Correzioni specifiche:**
- [2.1.3 Analisi dei Requisiti] Struttura dei requisiti: capire come usare "Tipologia" (argomentare se utile, rimuovere altrimenti);
- [3.1.15 Norme tipografiche] Documenti: scritti per esteso a meno di ripetizioni fastidiose, con la maiuscola come i ruoli (e.g. "Norme di Progetto");
- [3.1.17 Sigle] Nomi e sigle in corsivo;
- [3.2.2 Aspettative] Mancano i punti e virgola e il punto finale;
- [3.2.4 Versionamento] Rivedere questa sotto-sezione;
- [3.2.6 Struttura repository] In "Organizzazione del repository - Rami secondari...": "unititi";
- [3.2.6 Struttura repository] Citare "GitHub Flow" come best practice adottata;
- [3.4.2 Descrizione] Tipografia: punti e virgola elenchi;
- [3.4.3 Indicazioni] Tipografia: punti e virgola elenchi;
- [3.4.4 Verifica della documentazione] Tipografia: punti e virgola elenchi;
- [3.4.4 Verifica della documentazione] "Controllo della stesura del documento" -> " Controllo dell'aderenza alle convenzioni tipografiche e di stile adottate" (il documento è chiaramente già stato scritto);
- [4.1.1 Coordinamento] "Riunioni... Scaletta: ...": "segue usa" invece di "segue una";
- [4.2.1 Strumenti] Sezione GitHub: inserire link correttamente;
- [4.2 Infrastruttura] Generalmente non segue le convenzioni tipografiche e di stile adottate, rivedere con attenzione (poiché scritta prima della formalizzazione delle regole di stile);
- [4.3 Miglioramento] Segnare come TODO;
- [4.4 Formazione]
      1. Documentazione generica di overleaf invece che il "30 minutes";
      2. Spostare il link al "generatore tabelle latex" su Drive ed eliminare da qui;
      3. Aggiungere come sottopunti a GitHub:
             - Git: https://docs.github.com/en/get-started/using-git/about-git;
             - GitHub Flow: https://docs.github.com/en/get-started/quickstart/github-flow.
