### ISSUE TITLE
AdR-UC7 visualizzazione errore

### ISSUE THREAD

**Issue by Emanuele999-it** [merlunipd/login-warrior#81]
Descrivere l’errore generico che verrà richiamato ogni volta che servirà, prendere spunto dal vecchio UC3.

**Comment by mamprinmarco** [comment]
Se l'UC6 manuale utente ha anche un altro UC per il manuale dello sviluppatore, quindi UC7, questo UC non dovrebbe essere UC8?

**Comment by Emanuele999-it** [comment]
Sì, in realtà ci sono altri UC la cui numerazione si sovrappone. Ora inserisco una nuova issue per sistemarli
